### ISSUE TITLE
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

### ISSUE THREAD

**Issue by wsqat** [runa91/FRCNN_git#4]
Hi, thank you your github!
And, I run the code in $FRCNN_git， but get the error as the title.
Could you give me some advise?
The code as follows:
` ./experiments/scripts/faster_rcnn_end2end_new.sh 0 FRCNN_rot_models/VGGnet_fast_rcnn_iter_60000.ckpt data/building_data/`

**Comment by wsqat** [comment]
This problem is closed!

**Comment by wsqat** [comment]
I want to know why one image has many rect but just one angle?

**Comment by wsqat** [comment]
@runa91

**Comment by tcxia** [comment]
Hi， this problem how to slove?
